FROM maven:3-jdk-8 as builder
WORKDIR /app
COPY . .
RUN mvn package -P production

FROM m1c0l/alpine-openjdk-ffmpeg
WORKDIR /app
COPY videoEncoder ./
COPY --from=builder /app/target/videoprocessingservice-0.0.1-SNAPSHOT.jar ./service.jar
CMD java -jar service.jar
